# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9615da6e23155783baf6e45df147b367b0be324b192f36aa11776312e60e82463e8040c317425fb9a1ddaee633bb2d1f34f629ece6cbe2006c71ade2ef2af91c

test:
  secret_key_base: c5ad1559fe4a8fd66fb684ebc408d3b72fc23f25a80f49d5b33d22a9c2c458122be84cf85a89732572387adc94d0643147df0934eac1f87e2e9e757b063b87fd

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
